In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("covid_vaccine_statewise.csv")
df.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

In [4]:
df.shape

(7845, 24)

In [5]:
df.sample(frac=0.20)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
2788,16/02/2021,Himachal Pradesh,84718.0,2292.0,687.0,81911.0,2807.0,33749.0,48161.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81911.0
4501,05/03/2021,Maharashtra,1479034.0,46743.0,2341.0,1244617.0,234417.0,680964.0,563432.0,221.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1244617.0
4043,30/01/2021,Lakshadweep,807.0,19.0,12.0,807.0,0.0,623.0,184.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,807.0
4676,27/01/2021,Manipur,1873.0,95.0,19.0,1873.0,0.0,877.0,996.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1873.0
6180,16/02/2021,Rajasthan,626481.0,13994.0,4246.0,612615.0,13866.0,359118.0,253439.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,612615.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5361,17/03/2021,Nagaland,56257.0,6960.0,59.0,43476.0,12781.0,32042.0,11433.0,1.0,...,NaN,NaN,NaN,21246.0,17030.0,5189.0,NaN,NaN,NaN,43476.0
1247,22/07/2021,Bihar,21652372.0,662066.0,752.0,18344999.0,3307373.0,11764545.0,9883623.0,4204.0,...,10044302.0,6119739.0,5488331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3710,01/05/2021,Kerala,7425416.0,69210.0,594.0,6069726.0,1355690.0,2750902.0,3318069.0,755.0,...,NaN,NaN,NaN,621053.0,2329584.0,3118636.0,NaN,NaN,NaN,6069726.0
7525,30/04/2021,Uttarakhand,2079214.0,129050.0,680.0,1665065.0,414149.0,836549.0,828254.0,262.0,...,NaN,NaN,NaN,171391.0,767730.0,725771.0,NaN,NaN,NaN,1665065.0
1220,25/06/2021,Bihar,15512516.0,2273753.0,1956.0,13355865.0,2156651.0,8537977.0,6971740.0,2799.0,...,6280272.0,4614251.0,4617993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.loc[df.State=='Karnataka']

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
3393,16/01/2021,Karnataka,3810.0,256.0,235.0,3810.0,0.0,1835.0,1975.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3810.0
3394,17/01/2021,Karnataka,4506.0,1385.0,1139.0,4506.0,0.0,2373.0,2133.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4506.0
3395,18/01/2021,Karnataka,14755.0,1999.0,1502.0,14755.0,0.0,6122.0,8633.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14755.0
3396,19/01/2021,Karnataka,25142.0,2788.0,1993.0,25142.0,0.0,10492.0,14649.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25142.0
3397,20/01/2021,Karnataka,36705.0,3687.0,2517.0,36705.0,0.0,13421.0,23283.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36705.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3600,11/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3601,12/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3602,13/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3603,14/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3604,15/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.loc[df.State == "Karnataka"," Covaxin (Doses Administered)"].sum()

260352181.0

In [8]:
df.loc[df.State=='Karnataka'].sum()

Updated On                             16/01/202117/01/202118/01/202119/01/202120/01/...
State                                  KarnatakaKarnatakaKarnatakaKarnatakaKarnatakaK...
Total Doses Administered                                                    2300517146.0
Sessions                                                                     229117520.0
 Sites                                                                          992413.0
First Dose Administered                                                     1873329968.0
Second Dose Administered                                                     427187178.0
Male (Doses Administered)                                                   1061166867.0
Female (Doses Administered)                                                 1059022410.0
Transgender (Doses Administered)                                                335335.0
 Covaxin (Doses Administered)                                                260352181.0
CoviShield (Doses Administered)                                             2035227559.0
Sputnik V (Doses Administered)                                                 1186887.0
AEFI                                                                            370961.0
18-44 Years (Doses Administered)                                             507097304.0
45-60 Years (Doses Administered)                                             422134724.0
60+ Years (Doses Administered)                                               322769052.0
18-44 Years(Individuals Vaccinated)                                          162778610.0
45-60 Years(Individuals Vaccinated)                                          353393295.0
60+ Years(Individuals Vaccinated)                                            325517613.0
Male(Individuals Vaccinated)                                                         0.0
Female(Individuals Vaccinated)                                                       0.0
Transgender(Individuals Vaccinated)                                                  0.0
Total Individuals Vaccinated                                                 868523530.0
dtype: object

In [10]:
df.loc[df.State == "Karnataka","Male (Doses Administered)"].sum()

1061166867.0

In [11]:
df.loc[df.State == "Karnataka","Female (Doses Administered)"].sum()

1059022410.0

In [15]:
df.groupby('State')["Male (Doses Administered)","Female (Doses Administered)"].sum()

C:\Users\vamsh\AppData\Local\Temp\ipykernel_24668\2257615587.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('State')["Male (Doses Administered)","Female (Doses Administered)"].sum()

,Male (Doses Administered),Female (Doses Administered)
State,,
Andaman and Nicobar Islands,1.045375e+07,8.964974e+06
Andhra Pradesh,6.776694e+08,7.550539e+08
Arunachal Pradesh,3.061580e+07,2.463594e+07
Assam,3.557939e+08,3.035113e+08
Bihar,8.693946e+08,7.472145e+08
Chandigarh,2.920781e+07,2.216730e+07
Chhattisgarh,4.381651e+08,4.507674e+08
Dadra and Nagar Haveli and Daman and Diu,2.378859e+07,1.263831e+07
Delhi,4.239074e+08,3.051522e+08
Goa,4.484737e+07,4.060736e+07
Gujarat,1.326683e+09,1.127534e+09
Haryana,4.635441e+08,3.859696e+08
Himachal Pradesh,1.783223e+08,1.830803e+08
India,9.937298e+09,8.660417e+09
Jammu and Kashmir,2.712608e+08,1.857529e+08
Jharkhand,3.627754e+08,3.094526e+08
Karnataka,1.061167e+09,1.059022e+09
Kerala,6.668392e+08,7.480674e+08
Ladakh,1.142961e+07,9.239169e+06
Lakshadweep,2.762047e+06,2.179428e+06
Madhya Pradesh,1.088844e+09,8.958841e+08
Maharashtra,1.728077e+09,1.470241e+09
Manipur,4.128041e+07,3.228720e+07
Meghalaya,3.624802e+07,3.275265e+07
Mizoram,2.739356e+07,2.650217e+07
Nagaland,2.776194e+07,1.978228e+07
Odisha,6.252842e+08,5.523907e+08
Puducherry,2.348317e+07,2.321824e+07
Punjab,3.706496e+08,2.859032e+08
Rajasthan,1.297273e+09,1.171015e+09
Sikkim,2.308142e+07,1.954897e+07
Tamil Nadu,7.595978e+08,6.883262e+08
Telangana,5.185786e+08,4.795398e+08
Tripura,1.160976e+08,1.088415e+08
Uttar Pradesh,1.757450e+09,1.329731e+09
Uttarakhand,2.151377e+08,2.020295e+08
West Bengal,1.167820e+09,9.601327e+08